### ISSUE TITLE
Sceneform plugin causes Android studio crash on launch after converting object

### ISSUE THREAD

**Issue by terezo** [google-ar/sceneform-android-sdk#149]
Hi,

After converting an asset (not for every assets necessarily) Android studio keeps crashing. When I remove the Sceneform plugin everything works fine, I think it has something to do with Viewer.

**Asset (input + output):**
[asset.zip](https://github.com/google-ar/sceneform-android-sdk/files/2148226/asset.zip)

OS: Ubuntu 18.04 LTS, 64-bit
Graphics: Intel® HD Graphics 530 (Skylake GT2)

Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-23-generic

**Log:**
```Gtk-Message: 09:13:35.360: Failed to load module "canberra-gtk-module"
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/libfilament-jni7798815452253269660.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
FEngine (64 bits) created at 0x7efb7f24b010
Loading into viewer
Added 5 to scene
Loading into viewer
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007efc625d7ce8, pid=7959, tid=0x00007efc2c4af700
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b01) (build 1.8.0_152-release-1024-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x81cce8]  clean_ic_if_metadata_is_dead(CompiledIC*, BoolObjectClosure*, bool)+0x38
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/teraz/java_error_in_STUDIO_7959.log
AHE@0x00007efc5c0e98c0: 0xb0000000 i2c: 0x00007efc4d046c60 c2i: 0x00007efc4d046cb0 c2iUV: 0x00007efc4d046c84
Compiled method (c1)   26115 6568       3       java.awt.image.BufferedImage::<init> (1088 bytes)
 total in heap  [0x00007efc4dd8c650,0x00007efc4dd988e0] = 49808
 relocation     [0x00007efc4dd8c778,0x00007efc4dd8ceb0] = 1848
 constants      [0x00007efc4dd8cec0,0x00007efc4dd8cee0] = 32
 main code      [0x00007efc4dd8cee0,0x00007efc4dd94ce0] = 32256
 stub code      [0x00007efc4dd94ce0,0x00007efc4dd95038] = 856
 oops           [0x00007efc4dd95038,0x00007efc4dd95070] = 56
 metadata       [0x00007efc4dd95070,0x00007efc4dd95160] = 240
 scopes data    [0x00007efc4dd95160,0x00007efc4dd97c00] = 10912
 scopes pcs     [0x00007efc4dd97c00,0x00007efc4dd987b0] = 2992
 dependencies   [0x00007efc4dd987b0,0x00007efc4dd987d0] = 32
 nul chk table  [0x00007efc4dd987d0,0x00007efc4dd988e0] = 272
Compiled method (c1)   26115 6568       3       java.awt.image.BufferedImage::<init> (1088 bytes)
 total in heap  [0x00007efc4dd8c650,0x00007efc4dd988e0] = 49808
 relocation     [0x00007efc4dd8c778,0x00007efc4dd8ceb0] = 1848
 constants      [0x00007efc4dd8cec0,0x00007efc4dd8cee0] = 32
 main code      [0x00007efc4dd8cee0,0x00007efc4dd94ce0] = 32256
 stub code      [0x00007efc4dd94ce0,0x00007efc4dd95038] = 856
 oops           [0x00007efc4dd95038,0x00007efc4dd95070] = 56
 metadata       [0x00007efc4dd95070,0x00007efc4dd95160] = 240
 scopes data    [0x00007efc4dd95160,0x00007efc4dd97c00] = 10912
 scopes pcs     [0x00007efc4dd97c00,0x00007efc4dd987b0] = 2992
 dependencies   [0x00007efc4dd987b0,0x00007efc4dd987d0] = 32
 nul chk table  [0x00007efc4dd987d0,0x00007efc4dd988e0] = 272
Compiled method (c1)   26116 6568       3       java.awt.image.BufferedImage::<init> (1088 bytes)
 total in heap  [0x00007efc4dd8c650,0x00007efc4dd988e0] = 49808
 relocation     [0x00007efc4dd8c778,0x00007efc4dd8ceb0] = 1848
 constants      [0x00007efc4dd8cec0,0x00007efc4dd8cee0] = 32
 main code      [0x00007efc4dd8cee0,0x00007efc4dd94ce0] = 32256
 stub code      [0x00007efc4dd94ce0,0x00007efc4dd95038] = 856
 oops           [0x00007efc4dd95038,0x00007efc4dd95070] = 56
 metadata       [0x00007efc4dd95070,0x00007efc4dd95160] = 240
 scopes data    [0x00007efc4dd95160,0x00007efc4dd97c00] = 10912
 scopes pcs     [0x00007efc4dd97c00,0x00007efc4dd987b0] = 2992
 dependencies   [0x00007efc4dd987b0,0x00007efc4dd987d0] = 32
 nul chk table  [0x00007efc4dd987d0,0x00007efc4dd988e0] = 272
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by abramyan** [comment]
We'll take a look with those assets. Thanks.

**Comment by jrse** [comment]
have the same problem, are there any know workarounds yet?

**Comment by malik-at-work** [comment]
Fixed in 1.6

**Comment by marcspraragen** [comment]
Still having this exact issue with 1.9: trying to view a .sfb I converted from a .fbx There also doesn't seem to be

**Comment by Satish2804** [comment]
Still happening in 1.10  any fixes
