### ISSUE TITLE
Gray lines instead of camera feed in Galaxy S9 ARCore app builds

### ISSUE THREAD

**Issue by kipsten** [google-ar/sceneform-android-sdk#28]
When I build and run the "Hello Sceneform" and "Solar System" projects that I downloaded while following the Android Quickstart [https://developers.google.com/ar/develop/java/quickstart](https://developers.google.com/ar/develop/java/quickstart), all I see on my phone (a Galaxy S9) are these shifting gray/black lines
![screenshot_20180515-085346_hello sceneform_2](https://user-images.githubusercontent.com/1720758/40129185-a994f758-5901-11e8-8cd5-f7e81723cce7.jpg), with the moving ARCore hand/phone on top.

I can download and run ARCore apps from the store without a hitch. The S9 is the only ARCore-compatible phone I can test with. I'm using Android Studio 3.2 preview, Windows 10, ARCore 1.2, and Android 8.0.0.

When I try running on any emulator device, it immediately crashes before displaying anything, which is likely due to the fact that I don't think my desktop GPU supports OpenGL ES 3.1, based on the output when I run "adb logcat | grep eglMakeCurrent". Right now my goal is just to get it working on my phone, though.

**Comment by romainguy** [comment]
Please see https://github.com/google-ar/sceneform-android-sdk/issues/4#issuecomment-389673203 if you want instructions on how to setup an emulator that can run OpenGL ES 3.1. From your description you should be able to get it to work, but you'll need to pass a special flag.

**Comment by jpoernomoatsafe** [comment]
I'm also experiencing the same thing with the Galaxy S9 (physical device)
It's listed as one of the compatible phones.
I was able to run Sceneform on Asus Zenfone AR, though.

**Comment by malik-at-work** [comment]
What is the model number of the S9 device you have? 

https://developers.google.com/ar/discover/supported-devices does list the S9 as supported as long as the model number doesn't end in 0 or 8.

**Comment by malik-at-work** [comment]
We will look int this.

**Comment by malik-at-work** [comment]
We have reproduced this and are investigating.

**Comment by crosseveryriver** [comment]
Samsung galaxy S9+ SM-G965U1 has the same problem

**Comment by romainguy** [comment]
This issue has been fixed internally.

**Comment by malik-at-work** [comment]
Fixed in Sceneform V1.3

**Comment by F1nite1Up** [comment]
I'm on Sceneform 1.3.0 helloesceneform example and still getting the same grey strips problem.

I'm using Samsung Galaxy S9 SM-G965U1 (Android 8.0.0, API 26), ARCore 1.3.

![screenshot_20180627-101734_hello sceneform](https://user-images.githubusercontent.com/40640524/41990067-38ab0350-79f6-11e8-9cc5-c0c5b252e61d.jpg)

**Comment by malik-at-work** [comment]
Thank you for the report! This issue is very model specific. We've reopened the issue and the team will investigate.

**Comment by renyedi** [comment]
The team should seriously consider making S9 compatibility a release blocker. It is the AR Core capable device with the highest market share, probably by quite a margin.

**Comment by dcwill34** [comment]
I have also installed sceneform 1.3 and followed the NDK instructions from another possible solution and still getting the grey wavy lines. Using Samsung S9+ SM-G965U

**Comment by ReevesL** [comment]
@malik-at-work , since you note it's very model-specific, I'll add in another that doesn't work: Samsung S9+ SM-G965U1 (Android 8.0.0).

**Comment by curtism99** [comment]
Reporting in that a Samsung S9 SM-G960U version 8.0 behaves the same way and does not work correctly.

**Comment by AxesandGrinds** [comment]
Any update on this? I am getting the same display on emulator running AugmentedImage from Sceneform on my Pixel 2 XL.

**Comment by renanrhoden** [comment]
hey @malik-at-work , this fix is available somewhere? I have a S9+ with the same problem. Do you have any estimated date for the next release?

**Comment by malik-at-work** [comment]
Release may be imminent.  We can't give more specific info as this has to go through the normal release process which may change any date we gave out.

**Comment by nileshlg2003** [comment]
Just for the record, Same problem for me too on Galaxy S9 - G960U1. Hopefully release with fix is coming soon.

**Comment by dsternfeld7** [comment]
This should now be fixed in Sceneform 1.4. Please open a new issue if you are still seeing a similar problem on any devices.

**Comment by renyedi** [comment]
I can confirm that Sceneform 1.4 now works nicely with my `SM-G965U`. Thanks!

**Comment by AxesandGrinds** [comment]
E

**Comment by curtism99** [comment]
I'd like to report that I think I'm still having issues with my SM-G960U. I'm unsure if it's my code or if it's a Sceneform issue. I'm open to explore this issue more with someone.

**Comment by davidbeloo** [comment]
I can confirm that I have that issue on 1.3 and now on 1.5.1 it's working perfect.
Please make sure to move to 1.5.1 in:

1.  Your project build.gradle file:
     `classpath 'com.google.ar.sceneform:plugin:1.5.1'`

2.  Your app build.gradle file:
     `implementation "com.google.ar.sceneform:core:1.5.1"`
     `implementation "com.google.ar.sceneform.ux:sceneform-ux:1.5.1"`
