### ISSUE TITLE
Black artifact with plane renderer

### ISSUE THREAD

**Issue by JL-Vidinoti** [google-ar/sceneform-android-sdk#308]
When the plane renderer is enabled, some black artifacts may appear when the device is at some positions.
It happens with the `hellosceneform` sample. When I disable the plane renderer with `getArSceneView().getPlaneRenderer().setEnabled(false);` it does not seem to happen anymore.
However, when I hide it via `getArSceneView().getPlaneRenderer().setVisible(false);` for keeping the shadows, the problem also happens.

My device is a Samsung Galaxy S9 and I run Sceneform 1.4.0.
Does anybody else is experiencing this? How to solve it? 

See the screenshot below
![device-2018-09-06-091002](https://user-images.githubusercontent.com/35372626/45141480-3ff53980-b1b6-11e8-9f81-90d830a98d22.png)

See video:
https://photos.app.goo.gl/hAWsQn7HLPxqBf46A

**Comment by malik-at-work** [comment]
Are there other objects in the scene intersecting with the plane?

Have you added any lights to the scene or disabled any lights?

**Comment by malik-at-work** [comment]
Whats the exact model number of your device?

**Comment by JL-Vidinoti** [comment]
No, I did not change the `hellosceneform` sample.
The phone is a Samsung S8 SM-950F running Android 8.0.0

**Comment by dev4711** [comment]
I have the same issue tested on the following devices:
Samsung Galaxy S9 SM-G960F (Android 8.0.0)
Samsung Galaxy S9 Plus SM-G965F (Android 8.0.0)
Samsung Galaxy Note 8 SM-N950F (Android 7.1.1)
Samsung Galaxy A5 SM-A520F (Android 8.0.0)
Huawei P20 Pro CLT-L09 (Android 8.1.0)

Hopefully this can help you to analyse and fix this issue.

**Comment by malik-at-work** [comment]
This was fixed in the Sceneform 1.5 release.

**Comment by dev4711** [comment]
For me this is still reproducible in Sceneform 1.5 even though its not that often as in 1.4.

**Comment by JL-Vidinoti** [comment]
I confirm that this is not solved with Sceneform 1.5

**Comment by malik-at-work** [comment]
Thank you. I'll reopen the issue and try to track down if this missed the release train or if something else is going on.

**Comment by romainguy** [comment]
On what devices do you see the issue happen still?

**Comment by malik-at-work** [comment]
We tracked this down, the fix came in after the release train for 1.5.  It is committed to our code tree and will be in our next release.

**Comment by malik-at-work** [comment]
1.6 is released, please confirm this is resolved.

**Comment by dev4711** [comment]
@malik-at-work I can confirm this as fixed. I couldn't reproduce this issue with 1.6. Tested on the following devices:
* Samsung Galaxy Note 8 SM-N950F (Android 8.0.0)
* Samsung Galaxy Tab S4 SM-T830 (Android 8.1.0)
* Huawei P20 Pro CLT-L09 (Android 8.1.0)
