### ISSUE TITLE
Still can't make white background on SceneView with 1.6

### ISSUE THREAD

**Issue by yjoo9317** [google-ar/sceneform-android-sdk#452]
As title says,
still can't make complete white background with the latest version.
If transparent background possible, then I may make the container's background white but that's not the case here either.

issue #251 has a bug label for which I though that it will be fixed in the later version (= Version 1.6).
But apparently it hasn't been.

Is there any plan to fix it? 
If not, as the final resort for this issue, I may have to create the view from activity directly.

Thanks.

**Comment by afeozzz** [comment]
@romainguy 

material.baseColor.rgb = vec3(1.0, 1.0, 1.0); So it makes gray color.
Did you mean to do it via white texture?

**Comment by afeozzz** [comment]
I figured out that material.baseColor.rgb = vec3(5.0, 5.0, 5.0); gives a white color

but still waiting for a standard way of doing this

**Comment by ManuelTS** [comment]
Should now be resolved on 1.8.0 as the bug fixes state:
https://github.com/google-ar/sceneform-android-sdk/releases/tag/v1.8.0

**Comment by Jei** [comment]
It doesn't look like it's been resolved. I'm using Sceneform 1.10.0 and I'm still seeing a difference in the color applied to the scene's background.

**Comment by Dosssik** [comment]
@afeozzz 
Hi!
As far as standard way still doesn't work, could you please explain how to use the `material` to change the background of SceneView?

> I figured out that material.baseColor.rgb = vec3(5.0, 5.0, 5.0); gives a white color


>
